carts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
]

django_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.home, name='home'),
                  path('store/', include('store.urls')),
                  path('cart/', include('carts.urls')),
                  path('accounts/', include('accounts.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search')
]

carts/models.py
from django.db import models
from store.models import Product, Variant


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variants = models.ManyToManyField(Variant, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    # FIXME this makes no sense we should not be deleting products
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


class VariantManager(models.Manager):
    def colors(self):
        return super(VariantManager, self).filter(variant_category='color', is_active=True)

    def sizes(self):
        return super(VariantManager, self).filter(variant_category='size', is_active=True)


variant_category_choise = (
    ('color', 'color'),
    ('size', 'size')
)


class Variant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant_category = models.CharField(max_length=100, choices=variant_category_choise)
    variant_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariantManager()

    def __str__(self):
        return self.variant_value

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from store.models import Product, Variant
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    session_cart = request.session.session_key
    if not session_cart:
        session_cart = request.session.create()
    return session_cart


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variants = []
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST.get(key)
            try:
                variant = Variant.objects.get(product=product, variant_category__iexact=key,
                                              variant_value__iexact=value)
                product_variants.append(variant)
            except:
                pass
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
    cart.save()
    cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
    if cart_item_exists:
        cart_item = CartItem.objects.filter(product=product, cart=cart)
        ex_var_list = []
        id = []
        for item in cart_item:
            existing_variant = item.variants.all()
            ex_var_list.append(list(existing_variant))
            id.append(item.id)
        if product_variants in ex_var_list:
            index = ex_var_list.index(product_variants)
            item_id = id[index]
            cart_item = CartItem.objects.get(product=product, id=item_id)
            cart_item.quantity += 1
        elif product_variants:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            cart_item.variants.clear()
            cart_item.variants.add(*product_variants)
        cart_item.save()
    else:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        if product_variants:
            cart_item.variants.clear()
            cart_item.variants.add(*product_variants)
        cart_item.save()
    return redirect('cart')


def remove_from_cart(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, sub_total=0, tax=0, quantity=0, cart_items=None):
    color = request.GET.get('color')
    size = request.GET.get('size')
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            sub_total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = 1000  # TODO needs to be calculated here
    except ObjectDoesNotExist:
        pass  # ignore this exception as it does not affect usability

    context = {
        'sub_total' : sub_total,
        'quantity'  : quantity,
        'cart_items': cart_items,
        'tax'       : tax,
        'total'     : sub_total + tax
    }
    return render(request, 'store/cart.html', context)

store/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from carts.models import CartItem
from carts.views import _cart_id
from .models import Product, Category

PRODUCTS_PER_PAGE = 12


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True).order_by('id')
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
    paginator = Paginator(products, PRODUCTS_PER_PAGE)
    page = request.GET.get('page')
    page_products = paginator.get_page(page)
    product_count = products.count()
    context = {
        'products'     : page_products,
        'product_count': product_count
    }

    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        raise e
    if not product:
        product = get_object_or_404(Product, slug=product_slug)
    in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=product).exists()
    context = {
        'product': product,
        'in_cart': in_cart
    }
    return render(request, 'store/product_detail.html', context)


def search(request):
    context = {
        'product_count': 0
    }
    keyword = request.GET.get('keyword')
    if keyword:
        products = Product.objects.order_by('-created_date').filter(
            Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
        product_count = products.count()
        context.update({
            'products'     : products,
            'product_count': product_count
        })

    return render(request, 'store/store.html', context)

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->
            <div class="card">
                <div class="row no-gutters">
                    <aside class="col-md-6">
                        <article class="gallery-wrap">
                            <div class="img-big-wrap">
                                <a href="#"><img alt="{{ product.slug }}" src="{{ product.images.url }}"></a>
                            </div> <!-- img-big-wrap.// -->

                        </article> <!-- gallery-wrap .end// -->
                    </aside>
                    <main class="col-md-6 border-left">

                        <form action="{% url 'add_to_cart' product.id %}" method="POST">
                            {% csrf_token %}
                            <article class="content-body">

                                <h2 class="title">{{ product.product_name }}</h2>

                                <div class="mb-3">
                                    <var class="price h4">{{ product.price }}</var>
                                </div>

                                <p>{{ product.description }}</p>

                                {% if product.variant_set.colors %}
                                    <hr>
                                    <div class="row">
                                        <div class="item-option-select">
                                            <h6>Choose Color</h6>
                                            <label>
                                                <select name="color" class="form-control" required>
                                                    <option value="" disabled selected>Choose Color</option>
                                                    {% for variant in product.variant_set.colors %}
                                                        <option value="{{ variant.variant_value }}">{{ variant.variant_value }}</option>
                                                    {% endfor %}
                                                </select>
                                            </label>
                                        </div>
                                    </div> <!-- row.// -->
                                {% endif %}
                                {% if product.variant_set.sizes %}
                                    <div class="row">
                                        <div class="item-option-select">
                                            <h6>Select Size</h6>
                                            <label>
                                                <select name="size" class="form-control" required>
                                                    <option value="" disabled selected>Choose Size</option>
                                                    {% for variant in product.variant_set.sizes %}
                                                        <option value="{{ variant.variant_value | lower }}">{{ variant.variant_value | capfirst }}</option>
                                                    {% endfor %}
                                                </select>
                                            </label>
                                        </div>
                                    </div> <!-- row.// -->
                                    <hr>
                                {% endif %}
                                {% if product.stock <= 0 %}
                                    <h5 class="text-danger">Out of Stock</h5>
                                {% else %}
                                    <button type="submit" href="{% url 'add_to_cart' product.id %}"
                                            class="btn btn-primary"> <span
                                            class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i>
                                    </button>
                                {% endif %}
                            </article> <!-- product-info-aside .// -->

                        </form>
                    </main> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- card.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

            <br>

            <div class="row">
                <div class="col-md-9">

                    <header class="section-heading">
                        <h3>Customer Reviews </h3>

                    </header>

                    <article class="box mb-3">
                        <div class="icontext w-100">
                            <img src="{% static '/images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
                            <div class="text">
                                <span class="date text-muted float-md-right">24.04.2020 </span>
                                <h6 class="mb-1">Mike John </h6>

                            </div>
                        </div> <!-- icontext.// -->
                        <div class="mt-3">
                            <p>
                                Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip
                            </p>
                        </div>
                    </article>


                </div> <!-- col.// -->
            </div> <!-- row.// -->


        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/store.html
{% extends 'base.html' %}

{% block content %}

    <!-- ========================= SECTION PAGETOP ========================= -->
    <section class="section-pagetop bg">
        <div class="container">
            {% if 'search' in request.path %}
                <h2 class="title-page">Search Result</h2>
            {% else %}
                <h2 class="title-page">Our Store</h2>
            {% endif %}

        </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">

            <div class="row">
                <aside class="col-md-3">

                    <div class="card">
                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Categories</h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_1" style="">
                                <div class="card-body">

                                    <ul class="list-menu">
                                        <li><a href="{% url 'store' %}">All Products</a></li>
                                        {% for category in links %}
                                            <li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
                                        {% endfor %}
                                    </ul>

                                </div> <!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group  .// -->
                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Sizes </h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_4" style="">
                                <div class="card-body">
                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> XS </span>
                                    </label>

                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> SM </span>
                                    </label>

                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> LG </span>
                                    </label>

                                    <label class="checkbox-btn">
                                        <input type="checkbox">
                                        <span class="btn btn-light"> XXL </span>
                                    </label>
                                </div><!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group .// -->

                        <article class="filter-group">
                            <header class="card-header">
                                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true"
                                   class="">
                                    <i class="icon-control fa fa-chevron-down"></i>
                                    <h6 class="title">Price range </h6>
                                </a>
                            </header>
                            <div class="filter-content collapse show" id="collapse_3" style="">
                                <div class="card-body">

                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Min</label>
                                            <!-- <input class="form-control" placeholder="$0" type="number"> -->
                                            <select class="mr-2 form-control">
                                                <option value="0">$0</option>
                                                <option value="50">$50</option>
                                                <option value="100">$100</option>
                                                <option value="150">$150</option>
                                                <option value="200">$200</option>
                                                <option value="500">$500</option>
                                                <option value="1000">$1000</option>
                                            </select>
                                        </div>
                                        <div class="form-group text-right col-md-6">
                                            <label>Max</label>
                                            <select class="mr-2 form-control">
                                                <option value="50">$50</option>
                                                <option value="100">$100</option>
                                                <option value="150">$150</option>
                                                <option value="200">$200</option>
                                                <option value="500">$500</option>
                                                <option value="1000">$1000</option>
                                                <option value="2000">$2000+</option>
                                            </select>
                                        </div>
                                    </div> <!-- form-row.// -->
                                    <button class="btn btn-block btn-primary">Apply</button>
                                </div><!-- card-body.// -->
                            </div>
                        </article> <!-- filter-group .// -->

                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <main class="col-md-9">

                    <header class="border-bottom mb-4 pb-3">
                        <div class="form-inline">
                            <span class="mr-md-auto"><b>{{ product_count }}</b> items found</span>
                        </div>
                    </header><!-- sect-heading -->

                    <div class="row">
                        {% if products %}
                            {% for product in products %}
                                <div class="col-md-4">
                                    <figure class="card card-product-grid">
                                        <div class="img-wrap">
                                            <a href="{{ product.get_url }}">
                                                <img alt="{{ product.slug }}" src="{{ product.images.url }}"/>
                                            </a>
                                        </div> <!-- img-wrap.// -->
                                        <figcaption class="info-wrap">
                                            <div class="fix-height">
                                                <a href="{{ product.get_url }}"
                                                   class="title">{{ product.product_name }}</a>
                                                <div class="price-wrap mt-2">
                                                    <span class="price">{{ product.price }}</span>
                                                </div> <!-- price-wrap.// -->
                                            </div>
                                            {% if product.stock <= 0 %}
                                                <span class="text text-danger">Out of Stock <i
                                                        class="fas fa-window-close"></i></span>
                                            {% else %}
                                                {% if not product.variant_set.all %}
                                                    <a href="{% url 'add_to_cart' product.id %}"
                                                       class="btn btn-block btn-success">Add to cart </a>
                                                {% else %}
                                                    <a href="{{ product.get_url }}"
                                                       class="btn btn-block btn-info">View Variants </a>
                                                {% endif %}
                                            {% endif %}
                                        </figcaption>
                                    </figure>
                                </div> <!-- col.// -->
                            {% endfor %}
                        {% else %}
                            <div>
                                <h2>No Result Found. Please try again.</h2>
                            </div>
                        {% endif %}
                    </div> <!-- row end.// -->


                    <nav class="mt-4" aria-label="Page navigation sample">
                        {% if products.has_other_pages %}
                            <ul class="pagination">
                                {% if products.has_previous %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ products.previous_page_number }}">Previous</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled"><a class="page-link"
                                                                      href="#">Previous</a>
                                    </li>
                                {% endif %}

                                {% for i in products.paginator.page_range %}
                                    {% if products.number == i %}
                                        <li class="page-item active"><a class="page-link"
                                                                        href="?page={{ i }}">{{ i }}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if products.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ products.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="page-item disabled"><a class="page-link"
                                                                      href="#">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        {% endif %}
                    </nav>

                </main> <!-- col.// -->

            </div>

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}